### ISSUE TITLE
Resource Manager

### ISSUE THREAD

**Issue by Bytenol** [Webler-Group/webler-codes#47]
---

- [x] Create a file `RCompiler.ts` inside the `/helpers` directory.
- [x] Ensure `RCompiler.ts` is executable with the command `npm run compileResources`.
- [x] When `npm run compileResources` is executed, it should generate a single file `stringResources.ts` in the `/utils` directory.
- [x] `stringResources.ts` should export a default class `R` containing all the data from `/resources/strings/**` as a JavaScript object. The file should look like this:

    ```typescript
    export default class R {
      static #strings_en = { /* Content from /resources/strings/** */ }
      
      static getString(key: string, locale: string | null = "en"): string;
    }
    ```

- [x] Ensure `R` can be imported and, depending on the user's locale, `R.getString('appname')` returns `"webler"` when `locale="en"`.

---

**Comment by Mehran7kl** [comment]
@Bytenol merge your commit to this mew branch that I've just created.
